/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Pockey API Documentation
 * API documentation for the Pockey application
 * OpenAPI spec version: 1.0
 */
export interface SocialLoginCommand {
  snsId: string;
  nickname: string;
  profileImageUrl: string;
}

export interface StartSessionRequest {
  deviceId: string;
  receiverName: string;
}

export interface SubmitAnswerRequest {
  answer: string;
}

export type PostControllerGetPostsParams = {
  cursor?: string;
  limit: number;
};
