/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Pockey API Documentation
 * API documentation for the Pockey application
 * OpenAPI spec version: 1.0
 */
export interface SocialLoginCommand {
  snsId: string;
  nickname: string;
  profileImageUrl: string;
  deviceId?: string;
}

export interface StartSessionRequest {
  deviceId: string;
  receiverName: string;
}

export interface SubmitAnswerRequest {
  step: number;
  answer: string;
}

export type PostControllerGetPostsParams = {
  cursor?: string;
  limit: number;
};

export type RecommendSessionControllerStartSession201Step = 1;
export type RecommendSessionControllerStartSession201Type = "setup";
export type RecommendSessionControllerStartSession201 = {
  id: string;
  sessionId: string;
  step: RecommendSessionControllerStartSession201Step;
  question: string;
  options: string[];
  setupCount: number;
  occasionCount: number;
  questionCount: number;
  type: RecommendSessionControllerStartSession201Type;
};

export type RecommendSessionControllerSubmitAnswer201OneOfStep = 2 | 3 | 4;
export type RecommendSessionControllerSubmitAnswer201OneOfType = "setup";
export type RecommendSessionControllerSubmitAnswer201OneOf = {
  id: string;
  sessionId: string;
  step: RecommendSessionControllerSubmitAnswer201OneOfStep;
  question: string;
  options: string[];
  type: RecommendSessionControllerSubmitAnswer201OneOfType;
};

export type RecommendSessionControllerSubmitAnswer201OneOfFourStep = 5;
export type RecommendSessionControllerSubmitAnswer201OneOfFourOptionsItem = {
  key: string;
  title: string;
  description: string;
};

export type RecommendSessionControllerSubmitAnswer201OneOfFourType = "occasion";
export type RecommendSessionControllerSubmitAnswer201OneOfFour = {
  id: string;
  sessionId: string;
  step: RecommendSessionControllerSubmitAnswer201OneOfFourStep;
  question: string;
  options: RecommendSessionControllerSubmitAnswer201OneOfFourOptionsItem[];
  type: RecommendSessionControllerSubmitAnswer201OneOfFourType;
  description: string;
};

export type RecommendSessionControllerSubmitAnswer201OneOfEightStep =
  | 6
  | 7
  | 8
  | 9;
export type RecommendSessionControllerSubmitAnswer201OneOfEightType =
  "question";
export type RecommendSessionControllerSubmitAnswer201OneOfEight = {
  id: string;
  sessionId: string;
  step: RecommendSessionControllerSubmitAnswer201OneOfEightStep;
  question: string;
  options: string[];
  type: RecommendSessionControllerSubmitAnswer201OneOfEightType;
};

export type RecommendSessionControllerSubmitAnswer201OneOfOneoneItemProduct = {
  id: number;
  name: string;
  url: string;
  imageUrl: string;
  category: string;
  brand: string;
  price: number;
  priceRange: string;
  ageRange: string;
  situation: string[];
  intention: string[];
  friendshipLevel: string[];
  targetGender: string;
  tags: string[];
  nextPickProductIds: number[];
};

export type RecommendSessionControllerSubmitAnswer201OneOfOneoneItem = {
  product: RecommendSessionControllerSubmitAnswer201OneOfOneoneItemProduct;
  reason: string;
  minifiedReason: string;
  order: number;
};

export type RecommendSessionControllerSubmitAnswer201 =
  | RecommendSessionControllerSubmitAnswer201OneOf
  | RecommendSessionControllerSubmitAnswer201OneOfFour
  | RecommendSessionControllerSubmitAnswer201OneOfEight
  | RecommendSessionControllerSubmitAnswer201OneOfOneoneItem[];
