import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from "next/font/local";
import { TanstackQueryProvider } from "@/lib/tanstack-provider";
import { cn } from "@/lib/utils";
import "./globals.css";
import { MSWProvider } from "@/lib/msw-provider";

if (
  process.env.NEXT_RUNTIME === "nodejs" &&
  process.env.NODE_ENV === "development"
) {
  const { server } = await import("@/mocks/node");
  server.listen();
}

const pretendard = localFont({
  src: "../../node_modules/pretendard/dist/web/variable/woff2/PretendardVariable.woff2",
  display: "swap",
  weight: "45 920",
  variable: "--font-pretendard",
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          pretendard.variable,
          inter.variable,
          pretendard.className,
        )}
      >
        <MSWProvider>
          <TanstackQueryProvider>
            <div className="mx-auto h-dvh min-h-screen w-full max-w-full p-4 shadow-2xl sm:max-w-[390px]">
              {children}
            </div>
          </TanstackQueryProvider>
        </MSWProvider>
      </body>
    </html>
  );
}
