import type { Metadata } from "next"

import { Inter } from "next/font/google"
import localFont from "next/font/local"

import { cn } from "@/lib/utils"
import { TanstackQueryProvider } from "@/lib/tanstack-provider"

import "./globals.css"

const pretendard = localFont({
    src: "../../node_modules/pretendard/dist/web/variable/woff2/PretendardVariable.woff2",
    display: "swap",
    weight: "45 920",
    variable: "--font-pretendard",
})

const inter = Inter({
    subsets: ["latin"],
    variable: "--font-inter"
})

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={cn(
                pretendard.variable,
                inter.variable,
                pretendard.className
            )}>
                <TanstackQueryProvider>
                    {children}
                </TanstackQueryProvider>
            </body>
        </html>
    )
}
